### ISSUE TITLE
2018 Re-Focus

### ISSUE THREAD

**Issue by nelsonic** [dwyl/adoro#103]
We have not had the _time_ to focus on this project for the last couple of years 
because we have been working on _many_ other things. ⏳ 
We have delivered _several_ content-based web apps/sites to clients using _other_ CMSs
to _varying_ degrees of success. (_the clients have been "happy". I have been screaming inside!_)

We have _negotiated_ a _golden ticket_ with one of our valued clients to re-think CMS
for a project. 

## Todo

+ [ ] Remove "dead" (old/unused) code. (_we are splitting out the functionality into independently tested sub-modules_) - thank you to all who contributed to the original "alpha". ❤️ ✅ 
+ [ ] Focus on defining data types using _fields_: https://github.com/dwyl/fields 📝 
+ [ ] Use **append-only log** combined with a "column-oriented DBMS" to store data in PostgreSQL so that _any_ field/data can easily be compared and if necessary, "rolled back" with a single click.
+ [ ] Automatically render content creation forms based on the defined fields in that content type.
+ [ ] Focus on UX of content creation.

## Further Reading

+ https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying
+ https://github.com/orbitdb/ipfs-log
+ https://en.wikipedia.org/wiki/Column-oriented_DBMS
